services:
  - type: web
    name: aje-challenge
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MESSENGER_TRANSPORT_DSN
        value: doctrine://default?auto_setup=0
